### PR TITLE
fix: Canteen array from API is not ordered by type

### LINKED ISSUE #229: Canteen array from API is not ordered by type

### PR DESCRIPTION
**Pull request by Sasszem**
Fixed by implementing a sorting
Fixes #229

### CODE REVIEW

File: app/Http/Controllers/CanteensController.php [hunk 1]
```diff
@@ -41,8 +41,24 @@ public function byWeek(Request $request)
...
+
+        $canteens = $canteens_query->get()->toArray();
+        $maxDate = new Carbon();
+        if (0 !== count($canteens)) {
+            $maxDate = $canteens_query->latest('updated_at')->first()->updated_at;
+        }
+        $canteens_sorted = array();
+        foreach ($canteens as $canteen) {
+            usort($canteen['menus'], function ($item1, $item2) {
+                return $item1['type'] <=> $item2['type'];
```
Comment (TwoDCube) [inline app/Http/Controllers/CanteensController.php]: The task to do may have been ambiguous, so sorry for that, we have to order the `$canteen['menus']` by type given the correct order is `Soup`, `Main dish`, `Dessert`.

Comment (Sasszem) [reply app/Http/Controllers/CanteensController.php]: The `type` field can have values `0` for soup, `1` for main dish and `2` for desserts, so we can order simply by the value of `type`.
