### PR TITLE
Issue52: Use If-Modified-Since request header

### LINKED ISSUE #52: Use If-Modified-Since request header to help frontend cache resources efficiently.
We should process If-Modified-Since request headers (if sent) and return only with `200 OK` if there are updates found. If there are no updates on the server return `304 Not Modified` to the client.

### LINKED ISSUE #58: Bug: Duplicate field(images.post_id) in getPost request response

### LINKED ISSUE #59: Bug: unnecessary post_id in author.image in Posts

### LINKED ISSUE #60: Bug: Many-to-many relation Labels.posts is broken

### LINKED ISSUE #69: Bug: Week ends on Saturday midnight in CanteensController
This causes Sunday canteens to not show up anywhere

### PR DESCRIPTION
**Pull request by Sasszem**
If applied, this PR will add the handling of the `If-modified-since` request header for the following controller classes:
- `App\Http\Controllers\PostsController` for __Posts API__
- `App\Http\Controllers\EventsController` for __Events API__
- `App\Http\Controllers\CanteensController` for __Canteen API__

It will also fix issues #58, #59, #60, #69

Closes #52 
Fixes #58, fixes #59, fixes #60, fixes #69

### CODE REVIEW

File: app/Http/Controllers/CanteensController.php [hunk 1]
```diff
@@ -46,10 +44,41 @@ public function byWeek(Request $request)
...
         }
         
-        return $canteens;
+        
+        $modSince = self::_modSince($request);
+        
+        
+        // Find max date
+        $maxDate = new Carbon('1970-01-01');
+        $result->each(function ($post) use ($maxDate) {
```
Comment (TwoDCube) [inline app/Http/Controllers/CanteensController.php]: We should use the DB to get the latest posts' updated at field

File: app/Http/Controllers/CanteensController.php [hunk 2]
```diff
@@ -46,10 +44,41 @@ public function byWeek(Request $request)
...
-        if ($canteens->isEmpty()) {
+        
+        
+        return self::_after($request, $canteens);
+    }
+    
+    
+    private static function _modSince($request)
+    {
+        return new Carbon(str_replace(':', '', $request->header('If-modified-since', ': 1970-01-01')));
```
Comment (TwoDCube) [inline app/Http/Controllers/CanteensController.php]: Could you explain it why was it necessary?

Comment (Sasszem) [reply app/Http/Controllers/CanteensController.php]: For some weird reason, the `$request->header` line returns a line like `: Mon, 02 Jul 2018 00:00:00`. Notice the __:__ - it's an unexpected char and `Carbon` can not parse it. So we remove it with `str_replace`.
I've tried to use header names with the colon, but it always returns `null`, as it's not part of the header name.

File: app/Http/Controllers/CanteensController.php (hunk 1 above)
Comment (Sasszem) [reply app/Http/Controllers/CanteensController.php]: We only need to search in the results of the query, not in the whole data set, as **we don't need to re-send `Post id=20` just because `Post id=21` was modified.** We need to find the maximum `updated_at` in the result collection, which is ordered by its `date` field, so the `updated_at` fields is considered unordered, so the best search we can do is linear, which we do.
Of course, we could run the query _twice_, which would mean we have to search a much larger database - which is way less effective. We would also lose the ability to move date checking into a common function, as the second query would need to be the same as the first, except we order by `updated_at`
The only other way I can think of is to export the result into a new table, and query that. But then it needs sorting/maximum search, so we're at where we started _at best_.

**Comment by Sasszem** [comment]
Fixed, but not tested properly (yet).

**Comment by TwoDCube** [comment]
It was not in the issue, but we need to send Last-Modified header for all requests that can be cached using If-modified-since.

**Comment by Sasszem** [comment]
Need to merge #64 first

File: app/Http/Controllers/ControllerBase.php [hunk 3]
```diff
@@ -12,12 +12,16 @@ protected static function _after($request, $result, $maxDate)
...
+                $result = $query->get();
+                
+                if (!$result->isEmpty()) {
+                    $maxDate = $query->latest('updated_at')->first()->updated_at;
+                }
             }
         }
     
-    
+
```
Comment (TwoDCube) [inline app/Http/Controllers/ControllerBase.php]: There's 2 spaces on an empty line :P
